name: Auto-Document Terraform

on:
  push:
    paths:
      - 'iac-terraform/**/*.tf'
  pull_request:
    paths:
      - 'iac-terraform/**/*.tf'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify the version of Terraform you want to use

    - name: Download Terraform Docs
      run: |
        curl -LO https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz

    - name: Extract and Install Terraform Docs
      run: |
        tar -xzf terraform-docs-v0.16.0-linux-amd64.tar.gz
        sudo mv terraform-docs /usr/local/bin/
        rm terraform-docs-v0.16.0-linux-amd64.tar.gz

    - name: Generate Terraform Documentation
      run: |
        terraform-docs markdown iac-terraform > TEMP_README.md

    - name: Insert Terraform Documentation into README.md
      run: |
        # Extract the content before and after the placeholders
        sed -n '1,/<!-- BEGIN TERRAFORM DOCS -->/p' README.md > README_PREFIX.md
        sed -n '/<!-- END TERRAFORM DOCS -->/,$p' README.md > README_SUFFIX.md

        # Combine the files together
        cat README_PREFIX.md TEMP_README.md README_SUFFIX.md > README_NEW.md

        # Replace the old README.md with the new one
        mv README_NEW.md README.md

        # Cleanup
        rm TEMP_README.md README_PREFIX.md README_SUFFIX.md

    - name: Generate Documentation for Modules and Environments
      run: |
        for dir in $(find iac-terraform -type d -name 'modules' -or -name 'environments'); do
          for module in $(find $dir -maxdepth 1 -mindepth 1 -type d); do
            terraform-docs markdown $module > $module/README.md
          done
        done

    - name: Commit and Push Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git add iac-terraform/**/README.md
        git commit -m "Auto-generated Terraform documentation"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/sandman153/brand-build-llm.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
