name: Deploy Terraform with GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'Action to perform: deploy or destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

jobs:
  terraform:
    name: Terraform Operations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        env:
          TF_VAR_credentials: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir="./iac-terraform/environments/prod" init -input=false -reconfigure

      - name: Terraform Plan
        env:
          TF_VAR_credentials: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir="./iac-terraform/environments/prod" plan -input=false -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: ./iac-terraform/environments/prod/tfplan

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ github.event.inputs.action == 'deploy' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: ./iac-terraform/environments/prod/tfplan

      - name: Terraform Apply
        env:
          TF_VAR_credentials: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir="./iac-terraform/environments/prod" apply -input=false -auto-approve

  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        env:
          TF_VAR_credentials: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir="./iac-terraform/environments/prod" init -input=false -reconfigure

      - name: Terraform Destroy
        env:
          TF_VAR_credentials: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir="./iac-terraform/environments/prod" destroy -input=false -auto-approve
