name: Brand Build CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: deploy or delete'
        required: true
        default: 'deploy'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0

      - name: Set GOOGLE_CREDENTIALS Environment Variable
        run: |
          echo "GOOGLE_CREDENTIALS<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.GCP_SA_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: List Directory Structure
        run: |
          echo "Listing root directory:"
          ls -al
          echo "Listing iac-terraform directory:"
          ls -al ./iac-terraform
          echo "Listing environments directory:"
          ls -al ./iac-terraform/environments
          echo "Listing prod directory:"
          ls -al ./iac-terraform/environments/prod

  terraform:
    name: Terraform Operations
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir=./iac-terraform/environments/prod init

      - name: Terraform Plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir=./iac-terraform/environments/prod plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: ./iac-terraform/environments/prod/tfplan

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event.inputs.action == 'deploy'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: ./iac-terraform/environments/prod

      - name: Set GOOGLE_CREDENTIALS Environment Variable
        run: |
          echo "GOOGLE_CREDENTIALS<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.GCP_SA_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir=./iac-terraform/environments/prod apply -auto-approve tfplan

  delete:
    name: Delete
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.inputs.action == 'delete'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set GOOGLE_CREDENTIALS Environment Variable
        run: |
          echo "GOOGLE_CREDENTIALS<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.GCP_SA_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir=./iac-terraform/environments/prod init

      - name: Terraform Destroy
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform -chdir=./iac-terraform/environments/prod destroy -auto-approve
